In [ ]:
import os
from dotenv import load_dotenv
import pandas as pd

In [2]:
load_dotenv()
csv_path = os.getenv('DATA_RAW_PATH')

In [3]:
df = pd.read_csv(csv_path)
df

,nk_ota_localizer_id,fk_contact,date_purchase,time_purchase,place_origin_departure,place_destination_departure,place_origin_return,place_destination_return,fk_departure_ota_bus_company,fk_return_ota_bus_company,gmv_success,total_tickets_quantity_success
0,bc02d5245bec63b30ff1102fa273fc03f58bc9cc3f674e...,a7218ff4ee7d37d48d2b4391b955627cb089870b934912...,2018-12-26,15:33:35,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,50e9a8665b62c8d68bccc77c7c92431a1aa26ccbd38ed4...,0,0,8527a891e224136950ff32ca212b45bc93f69fbb801c3b...,1,89.09,1
1,5432f12612dd5d749b3be880e779989cf63b5efa4bcc4e...,37228485e0dc83d84d1bcd1bef3dc632301bf6cb22c8b5...,2018-12-05,15:07:57,10e4e7caf8b078429bb1c80b1a10118ac6f963eff098fd...,e6d41d208672a4e50b86d959f4a6254975e6fb9b088116...,0,0,36ebe205bcdfc499a25e6923f4450fa8d48196ceb4fa0c...,1,155.97,1
2,fb3caed9b2f1b6016d45ccddb19095476e61a2c85faa8e...,3467ec081e2421e72c96e7203b929d21927fd00b6b5f28...,2018-12-21,18:41:54,7688b6ef52555962d008fff894223582c484517cea7da4...,8c1f1046219ddd216a023f792356ddf127fce372a72ec9...,0,0,ec2e990b934dde55cb87300629cedfc21b15cd28bbcf77...,1,121.99,1
3,4dc44a6dd592b702feccb493d192210c86965aee684529...,ab3251a2be0f69713b8f97b0e9d1579e31551f4fd4facf...,2018-12-06,14:01:38,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,d6acb3c1a79e57bcc03d976cb4d98f56edccd4cf426392...,0,0,5f9c4ab08cac7457e9111a30e4664920607ea2c115a143...,1,55.22,1
4,aa34ed7fd0a6b405df2df1bf9f8d68e6df9b9a868a6181...,ceea0de820a6379f2c4215bddaec66c33994b304607e56...,2021-02-23,20:08:25,7688b6ef52555962d008fff894223582c484517cea7da4...,23765fc69c4e3c0b10f5d15471dc2245e2a19af16b513f...,0,0,48449a14a4ff7d79bb7a1b6f3d488eba397c36ef25634c...,1,45.31,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1741339,4e4f5fcded3e8b6915e05c6b9b504ec6830f723a831f68...,6b45fe9186baa7894b96bc7cdb801ce2c14427992217a5...,2023-12-29,19:47:12,2fca346db656187102ce806ac732e06a62df0dbb2829e5...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,0,0,3068430da9e4b7a674184035643d9e19af3dc7483e31cc...,1,156.00,1
1741340,8bcfd696bb80f3433449c1442e4c6bab55d4bce9fe4311...,be5b840765a5a2e316478410777a949fb6210cfe310fdf...,2019-08-01,10:06:37,7688b6ef52555962d008fff894223582c484517cea7da4...,37834f2f25762f23e1f74a531cbe445db73d6765ebe608...,0,0,ec2e990b934dde55cb87300629cedfc21b15cd28bbcf77...,1,106.93,2
1741341,1924fa1e8daf5821b3d062ac29d1ba56c70a54b41a177b...,72b052cfc6d04db064a5723e2faee0296e09d5e59689f1...,2019-01-18,10:28:42,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,ef2d127de37b942baad06145e54b0c619a1f22327b2ebb...,0,0,c17edaae86e4016a583e098582f6dbf3eccade8ef83747...,1,92.77,1
1741342,18b75368642c6c347fd00f56cd98322bb6d920b6a07545...,6b45fe9186baa7894b96bc7cdb801ce2c14427992217a5...,2023-01-08,23:57:55,2fca346db656187102ce806ac732e06a62df0dbb2829e5...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,0,0,35135aaa6cc23891b40cb3f378c53a17a1127210ce60e1...,1,294.99,1
1741343,113a96cafbc0fc70ab6cfba8bc017c57e720366265820c...,3b3d7594bde1223635a1f2fd8b547172e689ed8d711f84...,2023-01-14,21:40:39,2fca346db656187102ce806ac732e06a62df0dbb2829e5...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,0,0,1dfacb2ea5a03e0a915999e03b5a56196f1b1664d2f768...,1,158.95,1

In [4]:
df['date_purchase'] = pd.to_datetime(df['date_purchase'])

In [ ]:
df['time_purchase'] = pd.to_datetime(df['time_purchase'], format='%H:%M:%S', errors='coerce').dt.time

In [6]:
negativos = df[df['gmv_success'] < 0]
print(f"â†’ Existem {len(negativos)} valores negativos em gmv_success")
nulos = df[df['gmv_success'].isna()]
print(f"â†’ Existem {len(nulos)} valores nulos em gmv_success")

â†’ Existem 7 valores negativos em gmv_success
â†’ Existem 0 valores nulos em gmv_success

In [7]:
df = df[df['gmv_success'] >= 0]

In [11]:
df.to_parquet('transacoes_preparado.parquet')